[package]
name = "errc_fuzz"
version = "0.1.0"
authors = ["Dominik Maier <domenukk@gmail.com>", "Lukas Seidel"]
edition = "2018"

[dependencies]
unicornafl = { path = "../../unicornafl_bindings/", version="0.9.0-afl" }
capstone="0.6.0"
libc="0.2.66" 

[profile.release]
panic = "abort"
